CREATE BIGFILE TABLESPACE DEMO DATAFILE 'demo01.dbf' SIZE 10G AUTOEXTEND ON NEXT 100M MAXSIZE 50G;
CREATE USER COFFEESHOP IDENTIFIED BY demo DEFAULT TABLESPACE DEMO;
GRANT CREATE SESSION, RESOURCE, SELECT_CATALOG_ROLE TO COFFEESHOP IDENTIFIED BY demo;
ALTER USER COFFEESHOP QUOTA UNLIMITED ON DEMO;